name: "My Go-Based GitHub Action"
description: "Runs a custom Go program inside Docker"
author: "Your Name"
branding:
  icon: "terminal"
  color: "blue"

inputs:
  message:
    description: "Message to print"
    required: true
    default: "Hello from Go!"
  test-message:
    description: "Message to print"
    required: true
    default: "Hello from Go!"

outputs:
  result:
    description: "Processed message"

runs:
  using: "docker"
  image: "docker://public.ecr.aws/l7o7z1g8/actions/sonarqube-sast-actions:main-a826d5fca522735f794de51e0de7608b71df3cb8"  # Use prebuilt Docker image
  args:
    - ${{ inputs.message }}
    - ${{ inputs.test-message }}