name: Store Step ID Example

on: [push, workflow_dispatch]

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Store Step ID
        id: step1
        run: echo "STEP_ID=step1" >> $GITHUB_ENV

      - name: Step 2 - Use Step ID in Later Step
        run: echo "Step ID is: $STEP_ID"
