name: Step ID Example Workflow

on: [push, workflow_dispatch]

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Assign Step ID
        id: step_one
        run: echo "Hello from Step 1"

      - name: Step 2 - Use Previous Step ID
        run: echo "Step ID: ${{ steps.step_one.id }}"
