# This is a basic workflow to help you get started with Actions

name: Caller Workflow

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - resuable-workflow

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  call_workflow:
    # Calls the reusable workflow
    uses: SrimanPadmanabanCB/gha-action/.github/workflows/reusable.yaml@resuable-workflow
